name: CI/CD Workflow for Practical 2

# Triggers the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust Python version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (if applicable)
      - name: Run tests
        run: |
          pytest  # Ensure you have a `tests/` directory with test cases

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy your application (customize this step)
      - name: Deploy application
        run: |
          echo "Deploying the application..."
